version: '3.9'
services:
  # go-notifier-app:
  #   build:
  #     context: ..
  #     dockerfile: deployments/Dockerfile
  #   hostname: go-notifier-app
  #   container_name: go-notifier-app
  #   env_file:
  #     - .env
  #   restart: always
  #   ports:
  #     - 8071:8071
  #   networks:
  #     - go-notifier-network
  #   depends_on:
  #     - mysql

  mysql:
    image: mysql:8.1.0
    command: --default-authentication-plugin=mysql_native_password
    hostname: go-notifier-mysql
    container_name: go-notifier-mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root1
      MYSQL_DATABASE: go_notifier
      MYSQL_USER: admin
      MYSQL_PASSWORD: go_notifier
      # MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      # MYSQL_DATABASE: ${DB_NAME}
      # MYSQL_USER: ${DB_USERNAME}
      # MYSQL_PASSWORD: ${DB_PASSWORD}
    expose:
      - "3306"
    ports:
      - "23306:3306"
    volumes:
      - go-notifier-mysql-data:/var/lib/mysql
    restart: always
    networks:
      - go-notifier-network

  mysql-test:
    image: mysql:8.1.0
    command: --default-authentication-plugin=mysql_native_password
    hostname: go-notifier-mysql-test
    container_name: go-notifier-mysql-test
    env_file:
      - .env.test
    environment:
      MYSQL_ROOT_PASSWORD: root1
      MYSQL_DATABASE: go_notifier
      MYSQL_USER: admin
      MYSQL_PASSWORD: go_notifier
    ports:
      - "29306:3306"
    volumes:
      - go-notifier-mysql-test-data:/var/lib/mysql
    restart: always
    networks:
      - go-notifier-network
  rabbitmq:
    hostname: go-notifier-rabbitmq
    image: rabbitmq:3.9.7-management-alpine
    container_name: bodyfit-engine-rabbit-mq
    ports:
      - "5672:5672"
      - "15673:15672"
    restart: always
    networks:
      - go-notifier-network

volumes:
  go-notifier-mysql-data: ~
  go-notifier-mysql-test-data: ~

networks:
  go-notifier-network:
    name: go-notifier-network