// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	repository "go_notifier/internal/db/repository"

	mock "github.com/stretchr/testify/mock"
)

// CampaignRepository is an autogenerated mock type for the CampaignRepository type
type CampaignRepository struct {
	mock.Mock
}

// GetCampgignIdAndTimeByUUID provides a mock function with given fields: uuid
func (_m *CampaignRepository) GetCampgignIdAndTimeByUUID(uuid string) (*repository.CampaignIdTime, error) {
	ret := _m.Called(uuid)

	var r0 *repository.CampaignIdTime
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*repository.CampaignIdTime, error)); ok {
		return rf(uuid)
	}
	if rf, ok := ret.Get(0).(func(string) *repository.CampaignIdTime); ok {
		r0 = rf(uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.CampaignIdTime)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCampaignRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewCampaignRepository creates a new instance of CampaignRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCampaignRepository(t mockConstructorTestingTNewCampaignRepository) *CampaignRepository {
	mock := &CampaignRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
